FT-01: Creating App and Adding Common Layout
Jeysh-git/myproject pull request #1
Opened 2022-09-16 06:44 UTC by Jeysh-git

In this PR:
 - added plugin ember-bootstrap@2.6.1
 - added plugin ember-cli-sass@10.0.0
 - added plugin ember-svg-jar@2.3.3
 - added common main left navigation bar, header, footer, images.
 
output screenshot:
<img width="1440" alt="Screenshot 2022-09-16 at 11 39 30 AM" src="https://user-images.githubusercontent.com/101196204/190570301-2178ee0b-0453-40f5-89a5-eac1426c614d.png">

Figma-link: https://www.figma.com/file/i9whcNdWDHjHsXVdpoYyFh/New-Joinee?node-id=0%3A1

2022-10-07 08:52 UTC, Naomi-Mathews requested changes

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/templates/application.hbs
> +{{outlet}}
outlet should be before footer

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    background-color: $leftnav-color;
why is left, right , bottom and top required?

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    overflow: auto;
Why is overflow auto required? Are we expecting scroll?

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    top: 0px;
why is left, right , bottom and top required? Also when a value is 0 no need to specify % or px

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    top: 14px;
why is left and right required?

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    position: absolute;
why is position absolute required here? Acheive it using flex

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    position: absolute;
position absolute not required here

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    bottom:0%;
top and bottom properues not required

2022-10-07 08:52 UTC, Naomi-Mathews commented on app/styles/app.scss
> +    position: absolute;
why is position absolute required for this?

2022-10-10 12:50 UTC, Jeysh-git commented on app/templates/application.hbs
> +{{outlet}}
Updated.

2022-10-10 12:57 UTC, Jeysh-git commented on app/styles/app.scss
> +    background-color: $leftnav-color;
added appropriate styles.

2022-10-10 12:57 UTC, Jeysh-git commented on app/styles/app.scss
> +    overflow: auto;
removed overflow

2022-10-10 12:57 UTC, Jeysh-git commented on app/styles/app.scss
> +    top: 0px;
Done

2022-10-10 12:58 UTC, Jeysh-git commented on app/styles/app.scss
> +    top: 14px;
added appropriate styles

2022-10-10 12:58 UTC, Jeysh-git commented on app/styles/app.scss
> +    position: absolute;
added flex.

2022-10-10 12:58 UTC, Jeysh-git commented on app/styles/app.scss
> +    position: absolute;
removed.

2022-10-10 12:58 UTC, Jeysh-git commented on app/styles/app.scss
> +    bottom:0%;
Done.

2022-10-10 12:59 UTC, Jeysh-git commented on app/styles/app.scss
> +    position: absolute;
added appropriate styles

2022-10-13 05:59 UTC, Naomi-Mathews approved these changes

2022-10-13 06:01 UTC, merged